[profile.default]
src = "src/contracts"
out = "out"
libs = ["lib"]
solc = "0.8.19"
gas_price = 0
optimizer = true
optimizer_runs = 200

[profile.arbitrum-testnet]
eth_rpc_url = "https://sepolia-rollup.arbitrum.io/rpc"

[profile.arbitrum-mainnet]
eth_rpc_url = "https://arb1.arbitrum.io/rpc"

[etherscan]
arbitrumSepolia = { key = "${ARBISCAN_API_KEY}", url = "https://sepolia.arbiscan.io/api" }
arbitrumOne = { key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
